#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
use Symfony\Component\Console\Application;

require_once __DIR__.'/commands/sajo-functions.php';
require_once __DIR__.'/commands/make.php';
require_once __DIR__.'/commands/theme.php';

$application = new Application();
$application->add(new MakeTemplateCommand());
$application->add(new MakePartialCommand());
$application->add(new BuildPartialJsCommand());
$application->add(new ThemeNameCommand());
$application->run();
